# master makefile to build project, several targets have been defined with the aim to ease an
# easy handling of the most common task in a project like
# - make / all 	- Para construir el proyecto
# - make clean	- Remueve la carpeta Build con los archivos dentro de ella
# - make flash 	- Cargar/flashear nuestro programa a la tarjeta
# - make open	- Abre una conexion SW con la placa
# - make debug	- inicia una sesion de debugeo con OpenGDB
# - make test	- Ejecuta ceedling para unit testing con su code coverage

# Nombre del proyecto
TARGET = main
# Archivos a compilar
SRCS  = main.c startup_stm32f446xx.s
# linker file
LINKER = linker.ld

# directorios con los archivos fuente a compilar (.c y .s)
SRC_PATHS  = Autosar

# directorios con archivos header (.h)
INC_PATHS  = Autosar
INC_PATHS += Autosar/Libs
INC_PATHS += Autosar/Mcal
INC_PATHS += Autosar/Regs

# -------------------------------------------------------------------------------------------------
# NOTA: A partir de este punto, no modifiques nada a menos que sepas lo que haces
# ------------------------------------------------------------------------------------------------- 
TOOLCHAIN = arm-none-eabi
CPU = -mcpu=cortex-m4 -mthumb -mfloat-abi=soft

# banderas para el compilador
CFLAGS  = $(CPU)
CFLAGS += -O0                        # Compila con optimizacion de tamaños (O0, O1, O2, O3, Os)
CFLAGS += -g3                        # Nivel de informacion de debuggeo (g1, g2, g3)
CFLAGS += -ffunction-sections        # Crea una function section separada
CFLAGS += -fdata-sections            # Crea una data section separada
CFLAGS += -fno-builtin               # No reconoce funciones built-in que no empiecen con el prefijo ‘__builtin_’
CFLAGS += -std=c11                   # Compila con C11
CFLAGS += -Wall                      # Habilita los Warnings
CFLAGS += -pedantic                  # Para ser mas analitico en comprobaciones ANSI
CFLAGS += -Wstrict-prototypes        # Advertir si se declara o define una función sin especificar los tipos de argumentos
CFLAGS += -fsigned-char              # char es tratado como signed
CFLAGS += -fdiagnostics-color=always # Añade color a la salida de la terminal
CFLAGS += -fomit-frame-pointer       # No mantiene el frame pointer en un registro para funciones que no lo necesitan
CFLAGS += -fverbose-asm              # Coloca información de comentarios adicionales en el código de ensamblaje generado
CFLAGS += -MMD -MP

# Banderas de ensamblador
AFLAGS = $(CPU)

# Banderas del linkerw
LFLAGS  = $(CPU) 
LFLAGS += -Wl,--gc-sections
LFLAGS += --specs=rdimon.specs 			# linkeo con semihosting 
LFLAGS += --specs=nano.specs 			# version nano de stdlib
LFLAGS += -Wl,-Map=Build/$(TARGET).map	# Genera un map file 

# banderas para ccpcheck
LNFLAGS  = --inline-suppr       	# comentarios para suprimir warnings del lint
LNFLAGS += --quiet              	# Muestra solo información útil
LNFLAGS += --enable=warning,style 	# Habilita solo warnings
LNFLAGS += --error-exitcode=1		# retorna error si hay algun warnings
LNFLAGS += --std=c11            	# hace las comprobaciones contra C11
LNFLAGS += --template=gcc       	# Muestra advertencias en estilo gcc
LNFLAGS += --force              	# Evalua todas las sentencias #if
LNFLAGS += --platform=unix32    	# Revisa contra una plataforma unix32, aunque usemos arm32
LNFLAGS += --cppcheck-build-dir=Build/lint

# sustitucion de prefijos
OBJS = $(SRCS:%.c=Build/obj/%.o)
OBJS := $(OBJS:%.s=Build/obj/%.o)
DEPS = $(OBJS:%.o=%.d)

# Establece variables de directorios de source y header
VPATH = $(SRC_PATHS)
INCLS = $(addprefix -I ,$(INC_PATHS))

#---Construir proyecto----------------------------------------------------------------------------------
all : build $(TARGET)

$(TARGET) : $(addprefix Build/, $(TARGET).elf)
	$(TOOLCHAIN)-objcopy -Oihex $< Build/$(TARGET).hex
	$(TOOLCHAIN)-objdump -S $< > Build/$(TARGET).lst
	$(TOOLCHAIN)-size --format=berkeley $<

Build/$(TARGET).elf : $(OBJS)
	$(TOOLCHAIN)-gcc $(LFLAGS) -T $(LINKER) -o $@ $^

Build/obj/%.o : %.c
	$(TOOLCHAIN)-gcc $(CFLAGS) $(INCLS) $(SYMBOLS) -o $@ -c $<

Build/obj/%.o : %.s
	$(TOOLCHAIN)-as $(AFLAGS) -o $@ -c $<

-include $(DEPS)

.PHONY : build clean flash open debug test format

#---Make directory to place all the generated bynaries for build, docs, lint and test--------------
build :
	mkdir -p Build/obj

#---Erase fodler with program binaries-------------------------------------------------------------
clean :
	rm -rf Build

#---flash the image into the mcu-------------------------------------------------------------------
flash :
	openocd -f board/st_nucleo_f4.cfg -c "program Build/$(TARGET).hex verify reset" -c shutdown

#---open a debug server conection------------------------------------------------------------------
open :
	openocd -f board/st_nucleo_f4.cfg
#	JLinkGDBServer -if SWD -device stm32f446ze -nogui

#---launch a debug session, NOTE: is mandatory to previously open a debug server session-----------
debug :
	arm-none-eabi-gdb Build/$(TARGET).elf -iex "set auto-load safe-path /"

#---Run unit testing with code coverage using ceedling---------------------------------------------
test : build
	ceedling clobber
	ceedling gcov:all
